"""Add status column to User

Revision ID: 692786bc87ec
Revises: 
Create Date: 2025-11-15 01:19:16.735131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692786bc87ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
