"""Add rejection_reason column to Booking

Revision ID: 6b01a66e4509
Revises: 9337a56b1e16
Create Date: 2025-12-01 22:55:19.023195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b01a66e4509'
down_revision = '9337a56b1e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
