"""Add travel date/time columns to Booking

Revision ID: 9337a56b1e16
Revises: a981f2f26c86
Create Date: 2025-12-01 22:53:47.135536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9337a56b1e16'
down_revision = 'a981f2f26c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('travel_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('travel_time')
        batch_op.drop_column('travel_date')

    # ### end Alembic commands ###
