"""Add processed_by and processed_at to leave_request table

Revision ID: a981f2f26c86
Revises: 692786bc87ec
Create Date: 2025-11-20 12:14:48.349560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a981f2f26c86'
down_revision = '692786bc87ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['processed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('processed_by')

    # ### end Alembic commands ###
